export const initialRows = [
  {
    id: 0,
    carrier: "UPS",
    trackingNo: "1Z8152430368220883",
    status: "Outgoing",
    condition: "Good",
    sender: "Clancey, Cliff",
    recipient: "Forde, Tony",
    comments: "Lorem Ipsum",
  },
  {
    id: 1,
    carrier: "UPS",
    trackingNo: "1Z8152430368220883",
    status: "Incoming",
    condition: "Good",
    sender: "Clancey, Cliff",
    recipient: "Forde, Tony",
    comments: "Lorem Ipsum",
  },
  {
    id: 2,
    carrier: "UPS",
    trackingNo: "1Z8152430368220883",
    status: "Outgoing",
    condition: "Good",
    sender: "Clancey, Cliff",
    recipient: "Forde, Tony",
    comments: "Lorem Ipsum",
  },
  {
    id: 3,
    carrier: "UPS",
    trackingNo: "1Z8152430368220883",
    status: "Outgoing",
    condition: "Good",
    sender: "Clancey, Cliff",
    recipient: "Forde, Tony",
    comments: "Lorem Ipsum",
  },
  {
    id: 4,
    carrier: "UPS",
    trackingNo: "1Z8152430368220883",
    status: "Incoming",
    condition: "Good",
    sender: "Clancey, Cliff",
    recipient: "Forde, Tony",
    comments: "Lorem Ipsum",
  },
  {
    id: 5,
    carrier: "UPS",
    trackingNo: "1Z8152430368220883",
    status: "Outgoing",
    condition: "Good",
    sender: "Clancey, Cliff",
    recipient: "Forde, Tony",
    comments: "Lorem Ipsum",
  },
  {
    id: 6,
    carrier: "UPS",
    trackingNo: "1Z8152430368220883",
    status: "Incoming",
    condition: "Good",
    sender: "Clancey, Cliff",
    recipient: "Forde, Tony",
    comments: "Lorem Ipsum",
  },
];
